#!/bin/sh

set -eu

if [ "$#" -lt 1 ]; then
    echo "usage: $0 <output-directory>" >&2
    exit 64
fi

output_directory=$1
output_file=$output_directory/Versions.generated.swift

git_command=$(command -v git 2>/dev/null) || {
    echo "error: git was not found" >&2
    exit 1
}

mkdir -p "$output_directory"

if [ -n "${VG_VERSION:-}" ]; then
    version=$VG_VERSION
else
    version=$("$git_command" describe --tags 2>/dev/null) || version=
fi

if [ -n "${VG_COMMIT:-}" ]; then
    commit=$VG_COMMIT
else
    commit=$("$git_command" rev-parse HEAD 2>/dev/null) || commit=
fi

quote() {
    value=$1
    hashes=

    while contains "$value" "${hashes}\"" \
        || contains "$value" "\"${hashes}" \
        || contains "$value" "\\${hashes}"
    do
        hashes=${hashes}#
    done

    printf '%s"%s"%s' "$hashes" "$value" "$hashes"
}

contains() {
    case $1 in
        *"$2"*) return 0 ;;
        *) return 1 ;;
    esac
}

temporary_file=$(mktemp "${output_file}.XXXXXX")
trap 'rm -f "$temporary_file"' EXIT HUP INT TERM

{
    cat <<'EOF'
// This file is automatically generated by VersionGeneratorPlugin.
// Do not edit this file manually.

internal enum Versions {

EOF
    printf '    internal static nonisolated let version: String = '
    quote "$version"
    printf '\n    internal static nonisolated let commit: String = '
    quote "$commit"
    printf '\n}\n'
} > "$temporary_file"

mv "$temporary_file" "$output_file"
trap - EXIT HUP INT TERM
